name: run update_quotidien_demande_hq

on:
  push: # pour tester
  schedule:
    - cron: "30 1 * * *" # “At 01:30.”

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11" # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/workflows/requirements_gh.txt

      - name: execute python script # run main.py
        env:
          SOME_SECRET: ${{ secrets.SOME_SECRET }}
        run: python src/data/quotidien_demande_hq.py

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
